
import { helveticaNow } from "@/fonts/helvetica-now";
import "./globals.css";
import LenisProvider from "@/components/lenis/LenisProvider";
import nextI18nextConfig from "../../../next-i18next.config";
import ClientLocaleProvider from "./client-provider";



export function generateStaticParams() {
  return nextI18nextConfig.i18n.locales.map((locale) => ({ locale }));
}


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body
        className={`${helveticaNow.variable} antialiased`}
      >
        <ClientLocaleProvider locale={locale}>
          <LenisProvider>
            {children}
          </LenisProvider>
        </ClientLocaleProvider>
      </body>
    </html>
  );
}
